### ISSUE TITLE
SyntaxError: 'import *' not allowed with 'from .' when loading plugin.

### ISSUE THREAD

**Issue by NathanW2** [brushtyler/db_manager#1]
Getting the following error when loading the plugin in XP lastest build of QGIS:

/.qgis/python/plugins\db_manager\info_viewer.py", line 26
    from .db_plugins.plugin import *
SyntaxError: 'import *' not allowed with 'from .'

**Comment by brushtyler** [comment]
I think it's due to the version of python (2.5) on windows as I've used relative imports. I'm going to change them.

**Comment by brushtyler** [comment]
Should be fixed in 4139d16. Try again.
