### ISSUE TITLE
avoid numeric fields

### ISSUE THREAD

**Issue by procino** [brushtyler/db_manager#11]
Dear all,
when I import shapefile using DB Manager I want avoid numeric fied type within postgres/postgis (I want only float or integer field type). Is there a parameter that I can change within qgis plug-in or on postgres? In ogr2ogr for example i can change precision parameter in PRECISION=NO PRECISION=NO (https://gis.stackexchange.com/questions/191801/what-is-the-easiest-way-to-avoid-shapefile-columns-being-imported-as-postgis-nu).

Im using qgis 2.18 version.
Thank you in advance.

**Comment by brushtyler** [comment]
db_manager project was integrated into QGIS years ago.
Please report the issue on qgis/QGIS project instead.
