### ISSUE TITLE
Should 'Primary Key' be 'OBJECTID' instead? (Import Vector Layer)

### ISSUE THREAD

**Issue by thundersnow-spatial** [brushtyler/db_manager#8]
In the "Import vector layer" dialogue, the option for 'Primary Key' creates a new field of 'serial' type (in addition to the data you're already bringing in) and sets it as the primary key.

Is the purpose of this new column to be the 'primary key' or the 'objected' field? 

If I want to import a dataset that has an existing primary key column, one of non-serial type and unique values, I would like to use that, and be at least prompted to create the 'objectid' field instead, knowing that this will be mostly for QGIS display purposes - a column of unique values - rather than a column of values I will 'key' off of in relationships.

Any thoughts?

**Comment by brushtyler** [comment]
DBManager is now part of QGIS, please use hub.qgis.org to file a ticket for it.
BTW, if you insert the name of your primary key into the field called "Primary Key", importer do not add a new field.
